name: 'Label Issues'

on:
  workflow_dispatch:
  issues:
    types: [opened, closed, labeled]
  pull_request_target:
    types: [closed, labeled]
  schedule:
    - cron:  '0 * * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    if: github.repository_owner == 'TryGhost'
    steps:
      - uses: tryghost/actions/actions/label-actions@main
